Pull request to approve rspec test for Player and TicTacToe
fedgut/mv-ruby-03-tic-tac-toe pull request #5
Opened 2019-10-11 21:39 UTC by fedgut

2019-10-12 11:03 UTC, bolah2009 requested changes
Hi Team,

Please don't submit another CRR ( code review request) if other milestones are not completed yet.

Let's make sure #4  and #5 are merged to `develop` branch and `feature/spec` is rebased and in sync with the `develop` branch before submitting another CRR.

Fix linter errors/warnings

#### :recycle: Changes required.


-----

### Let's make this Pull Request look more professional.
  - [NEXT PROJECT]: Use meaningful commits messages. [Learn more here](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/) and Check [this awesome article](https://chris.beams.io/posts/git-commit/)
  - [REQUIRED] Use meaningful names for  Pull Requests.
  - [REQUIRED] Add a short summary of changes in the Pull Request description.

#### Rename PR
  ![rename PR](https://user-images.githubusercontent.com/36057474/63838245-ec569f80-c974-11e9-93a9-83a4db5c259f.gif)
-----
#### Update PR description
  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)

2019-10-12 11:03 UTC, bolah2009 commented on spec/tic_tac_toe_spec.rb
> +  end
This test is failing.

```ruby
Failures:

  1) TicTacToe#set should set the choosen number into the board
     Failure/Error: expect { game.set(5) }.to(change { game.board }.from((1..9).to_a).to(board_))
       expected `game.board` to have changed to [1, 2, 3, 4, "O", 6, 7, 8, 9], but is now [1, 2, 3, 4, "0", 6, 7, 8, 9]
     # ./spec/tic_tac_toe_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 0.04224 seconds (files took 0.46855 seconds to load)
9 examples, 1 failure

Failed examples:

rspec ./spec/tic_tac_toe_spec.rb:17 # TicTacToe#set should set the choosen number into the board
```

2019-10-12 11:03 UTC, bolah2009 commented on bin/main.rb
> +        name = name.gsub(/\W/, "")
All these lines could be in a single line, right? :thinking: 

```ruby
name = gets.chomp.gsub(/\d|\W/, "")
```

2019-10-12 11:03 UTC, bolah2009 commented on bin/main.rb
> +  until accept_players == true
using `until accept_players` should work since `until` is excepting true/false statement.

2019-10-14 17:48 UTC, fedgut commented
> Hi Team,
> 
> Please don't submit another CRR ( code review request) if other milestones are not completed yet.
> 
Heya! we understand the idea behind not opening a code review request until the prev. milestones are done, but if code review takes more than 24 hours, we can't move forward if we don't submit further code review request for more work done in the project.

2019-10-15 05:18 UTC, maelfosso approved these changes
# Congratulations :clap:  You did it :smile: 

**The project is approved** :+1: 

Sorry that your review took more than 24 hours. The next time, please, write us on Slack **fulltime students** channels. Really, sorry.

Good luck with the next project.

2019-10-15 13:19 UTC, merged